config/routes.rb
Rails.application.routes.draw do
  resources :partners
  resources :profiles
  resources :events
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/pages/:page" => "pages#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  def as_json(options = {}){
    :id => self.id,
    :title => self.name,
    :start => self.start_time,
    :end => self.end_time,
    :description => self.description,
    :allDay => self.allDay,
    }
  end

  default_scope {order('start ASC')}

end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @event = Event.new
    @eventsList = Event.all
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    # @event = Event.find(params[:id])
    # respond_to do |format|
    #   format.html {redirect_to events_path}
    #   format.js
    # end
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.save
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :body, :allDay, :start, :end, :url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def show
      @members=Profile.all
      @partners=Partner.all
      @events=Event.first(3)
      render template: "pages/#{params[:page]}"
      respond_to do |format|
        format.html
        format.json { render json: @geojson }
      end
    end

    @geojson =
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-122.67803, 45.524822]
      },
      properties: {
        name: 'Starve Ups WHQ',
        address: "220 NW 8th Ave",
        :'marker-color' => '#00607d',
        :'marker-symbol' => 'circle',
        :'marker-size' => 'medium'
      }
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-122.58544921875, 45.51686865305553]
      },
      properties: {
        name: 'Starve Ups Bend Headquarters',
        address: "740 NE 3rd St #3",
        :'marker-color' => '#00607d',
        :'marker-symbol' => 'circle',
        :'marker-size' => 'medium'
      }
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-123.06644439697266, 44.04242031836441]
      },
      properties: {
        name: 'Starve Ups Eugene Headquarters',
        address: "1290 Oak St",
        :'marker-color' => '#00607d',
        :'marker-symbol' => 'circle',
        :'marker-size' => 'medium'
      }
    }
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url, notice: 'Partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:company, :partnership, :industry, :website, :contactperson, :phone, :email, :since, :video)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.order('company ASC')
    @profile = Profile.new

  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:brand, :body, :company, :overview, :status, :industry, :founded, :membersince, :funding, :strategy, :exit, :website, :email )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/events/index.html.erb
<div class="sc_block container">

  <%= link_to "+ &nbsp; Event".html_safe, new_event_path, { class: "btn btn-success add-event-float text-white", style:"border-radius: 5px 0 0 5px", id: "new-event", :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#new-event-modal'} %>
  <div class="container-fluid">
    <div class='calendar my-4' style="color: #636c72">
    </div>
    <hr class="hidden-sm-up">

      <div class="col-sm-8 event-list hidden-sm-up">
        <% @eventsList.each do |event| %>
        <div class="row d-flex flex-nowrap justify-content-start align-items-center">
          <div class="col-xs-1 px-0">
            <h1 class="event-date mx-4"><%= event.start.strftime("%d")  %></h1>
          </div>
          <div class="col pl-4" style="border-left: 1px solid lightgrey">
            <h5 class="text-muted event-desc mb-0 pb-0" style=""><%= link_to event.title, event_path(event)%></h5>
            <p class="mt-0 pt-0">
            <span class="card-text text-muted">5&mdash;6PM |
            <% if event.exclusive %>
            MEMBERS ONLY</span></p>
            <% else %>
              PUBLIC</span></p>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
      <div class="modal fade" id="new-event-modal">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">New event details</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" id="new-event-form">
              <%= render "form" %>
            </div>
          </div>
        </div>
      </div>

  </div>
</div>

app/views/events/new.html.erb
<!-- # <%= render "form" %> -->

app/views/events/show.html.erb
<%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>&nbsp; Edit'.html_safe, edit_event_path(@event), :class=> "btn btn-info edit-float floating-button text-white", :style => "border-radius: 5px 0 0 5px", id: "edit-event", :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#edit-event-modal' %>

<%= link_to '<i class="fa fa-times" aria-hidden="true"></i>
 <span>&nbsp; &nbsp;Delete </span>'.html_safe, event_path(@event), :class => "btn rounded-left btn-danger delete-float floating-button text-white", :style => "z-index: 1; border-radius: 5px 0 0 5px", id: "delete-event", :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#delete-event-modal' %>

<div class="container">
  <div class="container-fluid text-muted">
    <img src="../images/Sumo-Suits.jpg" style="max-width: 300px" alt="">
    <h1 class="my-4 text-blue" style="">
      <%= @event.title %>
    </h1>
    <p class="mt-4" style="">
      March 8, 2017<br/>
      6&mdash;8:00PM |
      <!-- <%= @event.start.hour %>:<br/>
      <%= @event.start.month %>/<%= @event.start.day %> -->
    <% if @event.exclusive %>
      Members only<br/>
    <% else %>
      <span class="">Public event</span>
    <% end %>
      | <%= @event.chapter %><br/>
      <%= @event.location %>
    </p>
    <hr class="my-4">
    <h5 class="text-blue mb-0 subhead" style="">Details:</h5><br/>
    <p class="body-copy"><%= @event.body %></p>
  </div>
</div>


    <div class="modal fade" id="edit-event-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Edit event details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" id="edit-event-form">
            <%= render "form" %>
          </div>
        </div>
      </div>
    </div>

  <div class="modal fade" id="delete-event-modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="delete-member-form">
          <h5 class="display-5 pt-4 px-auto text-muted">Are you sure you want to delete this event?  </h5>
          <p class="pb-4 px-auto text-muted">You might miss it when it's gone.</p>
          <%= link_to 'Delete Forever', event_path(@event), method: :delete, :class => "btn btn-danger" %>
          <!-- <button class="btn btn-danger" type="button" name="button">Delete Forever</button> -->
        </div>
      </div>
    </div>
  </div>


<!-- TO DO_ MAKE DELETE BUTTON WORK -->

app/views/pages/calendar.html.erb
<div class="container-fluid">
  <div class='calendar'></div>
  <!-- <button class="btn btn-outline-success" type="button" name="new_event" id="new-event-button">Add an event</button> -->
  <%= link_to "events", new_event_path, class: "btn btn-outline-success", id: "new-event", remote: true %>
</div>

app/views/pages/home.html.erb
<!-- VIDEO BLOCK -->
<div class="block block-inverse text-center mb-4">
  <div class="block-foreground">
    <h1 class="block-title" style="letter-spacing:1px">Oregon's Startup Scalerator</h1>
    <h4 class="text-white" style="letter-spacing:1px">THE END-TO-END ACCELERATOR FOR FOUNDERS &amp; STARTUPS</h4>
  </div>
  <div class="block-background">
    <iframe id="bgvideo"  src="https://player.vimeo.com/video/119810871?autoplay=1&loop=1&title=0&byline=0&portrait=0&background=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    <div class="opacity-layer">
    </div>
  </div>
</div>

<!-- ABOUT BLOCK -->
<div class="container-fluid" id="about" style="background-color:#f4f4f4">
  <div class="container py-4" >
    <div class="row">
      <div class="col-sm-6 my-4">
        <h1 style="color:#616161">About Starve Ups</h1>
        <p class="mb-4" style="color:#616161">The only scalerator in Oregon for disruptive entrepreneurs in every industry. Starveups statistically changes the game for founders by increasing their likelihood of success. Our full-cycle approach and peer-to-peer mentorship method has been proven to help founders succeed. </p>
        <p class="mt-4" style="color:#616161">Compared to national startup averages, Starveups member companies are:</p>
        <div class="row d-flex mt-4" style="flex-wrap:nowrap">
          <div class="col-sm-4">
            <h1 class="text-center" style="font-size: 3em"><i class="fa fa-line-chart text-blue" aria-hidden="true"></i><br/></h1>
            <p class="text-blue text-center mb-4">6x more likely to stay in business</p>
          </div>
          <div class="col-sm-4">
            <h1 class="text-center" style="font-size: 3em"><i class="fa fa-usd text-blue" aria-hidden="true"></i></h1>
            <p class="text-blue text-center mb-4">5x more likely to raise funding</p>
          </div>
          <div class="col-sm-4">
            <h1 class="text-center" style="font-size: 3em"><i class="fa fa-handshake-o text-blue" aria-hidden="true"></i></h1>
            <p class="text-blue text-center mb-4">Nearly 3.5x more likely to exit</p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 my-4">
        <img src="../images/starveups_cycle.png" alt="Starveups businesses move from the stages of Survive to Strive to Thrive">
      </div>
    </div>
  </div>
</div>

<!-- PARALLAX BLOCK -->
<div class="block" style="background:url(../images/homebg2.jpg); background-attachment: fixed; background-size: auto">
</div>

<!-- MEMBERS logo block  -->
<div class="block">
  <div class="container">
    <div class="row">
      <h1 class="mx-auto mb-4">Member Companies</h1>
    </div>
    <div class="row text-center">
      <% if @members.any? %>
        <% @members.each do |member| %>
          <div class="col-sm-3 px-auto text-center py-4">
            <a href="/profiles/<%= member.id %>"><h5><%= member.company %></h5></a>
          </div>
        <% end %>
        <% else %>
        There are no members in the directory.
      <% end %>
    </div>
  </div>
</div>

<!-- EVENT block  -->
<div class="block" style="background:url(../images/homebg2.jpg); background-attachment: fixed; background-size: auto">
  <div class="row">
    <h1 class="mx-auto mb-4 text-white text-shadow">Don't Miss Our Next Event</h1>
  </div>
  <div class="row text-center mx-auto" style="max-width:960px">
    <% if @events.any? %>
      <% @events.each do |event| %>
        <div class="col-sm-4 my-4 rounded text-muted" >
          <div class="rounded-top" style="background:white">
            <a href="/events/<%= event.id %>"><img src="../images/event.png" alt="" style="width: 100%" class="px-3 pt-3"></a>
          </div>
          <div class="rounded-bottom" style="background: white; height: 12rem; position:relative">
            <h2 class="py-3 px-3"><%= link_to event.title, event_path(event) %></h2>
            <p class="px-3 small center-text" style="position:absolute; bottom:1rem; left:0; width: 100%"><%= event.start.strftime("%m/%d")%> | <%= event.chapter %> |
              <% if event.exclusive %>
                PRIVATE
              <% else %>
                PUBLIC
              <% end %>
            <!-- <p class="px-3"><%= event.body %></p> -->
          </div>
        </div>
      <% end %>
      <% else %>
        <p>There are no members in the directory.</p>
    <% end %>
  </div>
</div>

<!-- STRATEGIC PARTNER logo block  -->
<div class="block" id="partners" style="background-color:#f4f4f4">
  <div class="container">
    <div class="row">
      <h1 class="mx-auto mb-4">Strategic Partners</h1>
    </div>
    <div class="row text-center mb-4">
      <% if @partners.any? %>
        <% @partners.each do |partner| %>
          <div class="col-sm-3 partner px-auto text-center my-4 py-4" style="position:relative">
            <h5 class="my-4"><%= partner.company %></h5>
            <div class="hoverpartner col-sm-12 text-center rounded">
              <p class="text-center"><%= link_to partner.partnership, partner_path(partner), :class=>"my-auto" %></p>
              <!-- <p class="my-auto py-4"><%= partner.partnership %></p> -->
            </div>
          </div>
        <% end %>
        <% else %>
          <p>There are no Partners in the directory.</p>
      <% end %>
    </div>
  </div>
</div>

  <!-- SUBSCRIPTION BLOCK -->
  <div class="block text-center" style="padding:120px 0 120px 0; background-color: white">
    <div class="container-fluid my-auto">
      <h1 class="mb-4 text-blue">
        Don't miss our next event
      </h1>
      <form class="form-inline d-flex justify-content-center">
        <div class="input-group input-group-lg">
          <div class="input-group mb-2" >
            <input type="text" class="form-control" placeholder="Email" id="sizing-addon1">
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </span>
          </div>
        </div>
      </form>
      <span class="text-muted mt-2"><strong>We respect privacy.</strong> And never share your email address.</span>
    </div>
  </div>
</div>

<!-- MAP BLOCK -->
<div class="block map hidden-sm-down">
  <div id='map'>
  </div>
  <div class="portlandicon">
    <div class="col-sm-12 shadow rounded">
      <h1>Starve Ups Headquarters</h1>
      <p class="small">220 NW 8th Ave.<br/>
      Portland, OR 97209<br/>
      <a href="mailto:contactus@starveups.com" class="">contactus@starveups.com</a></p>
    </div>
  </div>
</div>

<script type="text/javascript">
    mapboxgl.accessToken = 'pk.eyJ1IjoibGlzdGEiLCJhIjoiY2l6aXV5MXY3MDJ0MDJ4b3dyb2ZxYm04eSJ9.t7rJNY6xP0PeeOODFzO4EA';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/lista/ciziz384t00142sn5idxy1hjo',
        center: [-121.974020, 44.893307],
        zoom: 7
    });
    map.scrollZoom.disable();

</script>

<!-- ADDRESS BLOCK -->
<div class="block text-center text-white" id="contact" style="padding:120px 0 120px 0; background-color: #295D85">
  <div class="container my-auto">
    <div class="row">
      <div class="col-sm-4 my-4">
        <h3 class="text-white">Portland, OR</h3>
        <p><strong>Starve Ups HQ</strong><br/>
          220 NW 8th Ave.<br/>
          Portland, OR 97209<br/>
​         <a href="mailto:contactus@starveups.com" class="text-white">contactus@starveups.com</a>
        </p>
      </div>
      <div class="col-sm-4 my-4">
        <h3 class="text-white">Bend, OR</h3>
        <p><strong>Starve Ups HQ</strong><br/>
          220 NW 8th Ave.<br/>
          Portland, OR 97209<br/>
​        <a href="mailto:contactus@starveups.com" class="text-white">contactus@starveups.com</a>
        </p>
      </div>
      <div class="col-sm-4 my-4">
        <h3 class="text-white">Eugene, OR</h3>
        <p><strong>Starve Ups HQ</strong><br/>
          220 NW 8th Ave.<br/>
          Portland, OR 97209<br/>
​        <a href="mailto:contactus@starveups.com" class="text-white">contactus@starveups.com</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/partners/edit.html.erb
<h1>Editing Partner</h1>

<%= render 'form', partner: @partner %>

<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Partners</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Partnership</th>
      <th>Industry</th>
      <th>Website</th>
      <th>Contactperson</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Since</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partners.each do |partner| %>
      <tr>
        <td><%= partner.company %></td>
        <td><%= partner.partnership %></td>
        <td><%= partner.industry %></td>
        <td><%= partner.website %></td>
        <td><%= partner.contactperson %></td>
        <td><%= partner.phone %></td>
        <td><%= partner.email %></td>
        <td><%= partner.since %></td>
        <td><%= partner.video %></td>
        <td><%= link_to 'Show', partner %></td>
        <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
        <td><%= link_to 'Destroy', partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partner', new_partner_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/index.html.erb
<%= link_to "+ &nbsp; Member".html_safe , new_profile_path, { class: "btn btn-success floating-button add-float text-white", :style => "z-index: 1; border-radius: 5px 0 0 5px", id: "new-profile", :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#new-profile-modal'} %>


<div class="background-grey">
  <div class="container">

    <!-- <div class="sort-members py-2 shadow-nav hidden-sm-up" style="background-color:#353535">
      <h3 class="pt-2 mx-4 text-white">Browse Members</h3>
      <hr class="my-1">
      <ul class="nav d-flex py-0 align-items-center">
        <li class="nav-item ml-4">
          <a class="nav-link active" href="#">A&mdash;Z</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Industry</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Stage</a>
        </li>
      </ul>
    </div> -->
    <div class="sort-members pt-4 ml-4">
      <h3 class="pt-2 ml-2">Browse Members</h3>
      <div class="d-flex row my-4" style="flex-wrap:nowrap">
        <h5><strong><a class="mx-4" href="#">A&mdash;Z</a></strong></h5>
        <h5><strong><a class="mr-4" href="#">Industry</a></strong></h5>
        <h5><strong><a class="" href="#">Stage</a></strong></h5>
      </div>
      <hr>
    </div>


  <div class="container hidden-sm-up text-muted">
    <!-- <h3 class="pt-4">Member Directory</h3> -->
    <div class="col-sm-6 directory shadow rounded list-group" style="border-top: 1px solid #ddd">
      <% if @profiles.any? %>
        <% @profiles.each do |profile| %>
          <div class="list-group-item list-group-item-action pl-0 border-right-0 border-left-0">
            <% if profile.status === "Survive" %>
              <img class="card-profile-img rounded-circle ml-3 hidden-md-up" src="../images/starve_ups_stage-01.png" style="width: 2rem">
            <% elsif profile.status === "Strive" %>
              <img class="card-profile-img rounded-circle ml-3 hidden-md-up" src="../images/starve_ups_stage-02.png" style="width: 2rem">
            <% elsif profile.status == "Thrive" %>
              <img class="card-profile-img rounded-circle ml-3 hidden-md-up" src="../images/starve_ups_stage-03.png" style="width: 2rem">
            <% end %>
            <h4 class="mb-0 ml-0"><%= link_to profile.company, profile_path(profile), :class => "text-muted pl-3 list-members" %></h4>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="container mx-4 hidden-xs-down text-muted">
    <div class="card-group">
      <div class="row d-flex flex-wrap text-center mt-4">
        <% if @profiles.any? %>
          <div class="row">
            <% @profiles.each do |profile| %>
              <div class="col-md-3 mb-4">
                <div class="card text-muted shadow" style="border-radius: 8px">
                  <img class="card-img-top hidden-xs-down white-border" style="background-image: url(../images/profile_preview2.png); height: 100px; width: auto; border-radius: 8px 8px 0 0" alt="">
                  <div class="card-block pb-0">
                    <% if profile.status === "Survive" %>
                      <img class="card-profile-img rounded-circle shadow-nav hidden-xs-down white-border" src="../images/starve_ups_stage-01.png" style="width: 50px; margin-top: -4rem">
                    <% elsif profile.status === "Strive" %>
                      <img class="card-profile-img rounded-circle shadow-nav hidden-xs-down white-border" src="../images/starve_ups_stage-02.png" style="width: 50px; margin-top: -4rem">
                    <% elsif profile.status == "Thrive" %>
                      <img class="card-profile-img rounded-circle shadow-nav hidden-xs-down white-border" src="../images/starve_ups_stage-03.png" style="width: 50px; margin-top: -4rem">
                    <% end %>
                    <h4 class="card-title mb-2"><%= link_to profile.company, profile_path(profile)%></h4>
                    <p class="card-text" style=""><%= profile.industry %></p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="new-profile-modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">New Member Details</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="new-profile-form">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
  </div>

</div>